const SOURCE_COMMIT='26672e06427c12c61536ce1bd93dae7442944681';
const MODULE_BASE=`https://cdn.jsdelivr.net/gh/vaibhavkedarisetti/fruit-fly-lab@${SOURCE_COMMIT}/web`;
const DATA_BASE=`https://raw.githubusercontent.com/vaibhavkedarisetti/fruit-fly-lab/${SOURCE_COMMIT}/web/data`;
const EXPECTED_BYTES={connectome:22951784,neurons:3481375};
let decodeConnectome,Session,session=null,meta=null,neurons=null,running=false,loopTimer=null,tickMs=5,lastStimulusAt=-Infinity;
let contactUntil=-Infinity,contactStrength=0,contactSide=0;
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const send=(type,payload={},transfer)=>{const msg={type,...payload};transfer?postMessage(msg,transfer):postMessage(msg);};

async function fetchWithTimeout(url,options={},timeoutMs=120000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(url,{...options,signal:c.signal});}finally{clearTimeout(t);}}
async function fetchBuffer(url,label,expected){const r=await fetchWithTimeout(url,{mode:'cors',cache:'force-cache'});if(!r.ok)throw new Error(`${label} download failed: HTTP ${r.status}`);const total=expected||Number(r.headers.get('content-length'))||0;if(!r.body){const b=await r.arrayBuffer();send('progress',{label,loaded:b.byteLength,total:total||b.byteLength});return b;}const rd=r.body.getReader(),chunks=[];let loaded=0;for(;;){const {done,value}=await rd.read();if(done)break;chunks.push(value);loaded+=value.byteLength;send('progress',{label,loaded,total});}const out=new Uint8Array(loaded);let off=0;for(const ch of chunks){out.set(ch,off);off+=ch.byteLength;}if(expected&&loaded!==expected)throw new Error(`${label} size mismatch: ${loaded}`);return out.buffer;}
function decodeNeurons(buffer,n){let o=0;const root=new BigInt64Array(buffer,o,n);o+=n*8;const pos=new Float32Array(buffer,o,n*3);o+=n*12;const type=new Uint16Array(buffer,o,n);o+=n*2;const cls=new Uint8Array(buffer,o,n);o+=n;const side=new Uint8Array(buffer,o,n);o+=n;const sign=new Int8Array(buffer,o,n);return{root,pos,type,cls,side,sign};}

async function boot(){try{send('status',{message:'loading simulator'});const [e,s]=await Promise.all([import(`${MODULE_BASE}/js/engine.js`),import(`${MODULE_BASE}/js/sim.js`)]);decodeConnectome=e.decodeConnectome;Session=s.Session;send('status',{message:'loading connectome metadata'});const mr=await fetchWithTimeout(`${DATA_BASE}/meta.json`,{mode:'cors',cache:'force-cache'},30000);if(!mr.ok)throw new Error(`metadata download failed: ${mr.status}`);meta=await mr.json();send('status',{message:'loading connectome graph'});const [cb,nb]=await Promise.all([fetchBuffer(`${DATA_BASE}/connectome.bin`,'connectome',EXPECTED_BYTES.connectome),fetchBuffer(`${DATA_BASE}/neurons.bin`,'neurons',EXPECTED_BYTES.neurons)]);const connectivity=decodeConnectome(cb,meta.n,meta.nnz);neurons=decodeNeurons(nb,meta.n);session=new Session(connectivity,meta,7);const positions=neurons.pos.slice();send('ready',{n:meta.n,nnz:meta.nnz,dataset:meta.dataset,positions},[positions.buffer]);}catch(error){send('error',{message:error?.name==='AbortError'?'brain asset download timed out':String(error?.message||error)});}}

function contactOverlay(now){if(!session||now>=contactUntil||contactStrength<=0)return;const az=contactSide<0?-42:contactSide>0?42:0;const s=contactStrength;for(const a of [az,0])session.addLooming({azimuth_deg:a,elevation_deg:-8,half_size_mm:7+s*7,speed_mm_s:420+s*620,start_distance_mm:25,max_half_angle_deg:78});}
function applyContact(m){if(!session)return;contactStrength=clamp(Number(m.strength)||.6,0,1);contactSide=m.side==='left'?-1:m.side==='right'?1:0;contactUntil=session.engine.tMs+180;}

function applyVision(v){if(!session)return;const now=session.engine.tMs;if(now-lastStimulusAt<18)return;lastStimulusAt=now;session.clearStimuli();const sal=clamp(Number(v.salience)||0,0,1);const dark=clamp(Number(v.darkOnset)||0,0,1);const list=Array.isArray(v.stimuli)?v.stimuli.filter(x=>Number.isFinite(x?.strength)&&x.strength>0).sort((a,b)=>b.strength-a.strength).slice(0,18):[];for(const st of list){const base=clamp(Number(st.strength)||0,0,1);const local=clamp(Number(st.salience)||0,0,1);const intensity=clamp(base*(1+sal*.35+local*.25),0,1);if(intensity<.02)continue;session.addLooming({azimuth_deg:clamp(Number(st.azimuth_deg)||0,-100,100),elevation_deg:clamp(Number(st.elevation_deg)||0,-55,55),half_size_mm:2.8+intensity*11,speed_mm_s:70+intensity*680+sal*120+dark*100,start_distance_mm:30+(1-intensity)*82,max_half_angle_deg:78});}if(!list.length){for(const sector of [{k:'left',a:-38},{k:'center',a:0},{k:'right',a:38}]){const m=clamp(Number(v[sector.k])||0,0,1);if(m>.04)session.addLooming({azimuth_deg:sector.a,elevation_deg:0,half_size_mm:3+m*9,speed_mm_s:80+m*560,start_distance_mm:38,max_half_angle_deg:72});}}contactOverlay(now);}

function loop(){if(!running||!session)return;const t0=performance.now();const frames=session.advance(tickMs);const wall=performance.now()-t0;const f=frames.at(-1);if(f){const active=[];const ws=session.windowSum;for(let i=0;i<ws.length&&active.length<3500;i++)if(ws[i]>0)active.push(i);send('frame',{frame:{t_ms:f.t_ms,active_neurons:f.active_neurons,mean_rate_hz:f.mean_rate_hz,channels:f.channels,dn_rates:f.dn_rates,proboscis_drive:f.proboscis_drive,escape_laterality:f.escape_laterality,body:f.body,active_idx:active,wall_ms:wall}});}loopTimer=setTimeout(loop,Math.max(0,tickMs-wall));}

onmessage=(e)=>{const m=e.data||{};try{if(m.cmd==='boot')return boot();if(m.cmd==='play'){running=true;if(!loopTimer)loop();return;}if(m.cmd==='pause'){running=false;if(loopTimer)clearTimeout(loopTimer);loopTimer=null;return;}if(m.cmd==='vision'){applyVision(m.vision||{});return;}if(m.cmd==='contact'){applyContact(m);return;}if(m.cmd==='reset'){if(session)session.reset((m.seed??Date.now())&0xffff);lastStimulusAt=-Infinity;contactUntil=-Infinity;contactStrength=0;return;}if(m.cmd==='speed'){tickMs=clamp(Number(m.value)||5,1,20);}}catch(error){send('error',{message:String(error?.message||error)});}};
